### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by tritonas00** [cryham/ogre3ter-demo#1]
So, i used the scripts to build latest ogre-next master branch and my directory structure is:

```
/home/babis/Files/Ogre/ogre-next/
/home/babis/Files/Ogre/ogre-next-deps/
/home/babis/Files/ogre3ter-demo/
```

I `cd` in ogre3ter-demo and then `cmake .`

```
CMake Error at CMake/Dependencies/OGRE.cmake:261 (file):
  file failed to open for reading (No such file or directory):

    /home/babis/Files/ogre3ter-demo/Dependencies/Ogre/build/RelWithDebInfo/include/OgreBuildSettings.h
Call Stack (most recent call first):
  CMakeLists.txt:34 (setupOgre)
  ```

`OgreBuildSettings.h` is in `/home/babis/Files/Ogre/ogre-next/build/Release/include/`

Using Arch linux btw.

**Comment by cryham** [comment]
Strange.
I have this file also there `/Ogre/ogre-next/build/Release/include/OgreBuildSettings.h`
Must have been something inside OGRE.cmake that used RelWithDebInfo
Perhaps just copy the file from Release into RelWithDebInfo?
Well, I'm not sure how this should be done properly.

**Comment by tritonas00** [comment]
Welp i copied everything by hand, it compiled. But i can't select Renderer, the gui crashes:

```
Error: Shell widget menu has zero width and/or height
```

This is a known issue but i can't remember how i fixed it before lol

**Comment by tritonas00** [comment]
Absolutely gorgeous great work!

![kk](https://user-images.githubusercontent.com/2660424/197079442-d0ae23ef-dc50-4f2e-ad17-c40af75224c8.png)

**Comment by cryham** [comment]
Cool. Good to see it working.
Yes, I had this issue with closing Ogre dialog too. It happens when binary starts in folder with no plugins.cfg or wrong plugins.cfg I think. And in my repo I have plugins.cfg and resources2.cfg files in `bin\Debug` and `bin\Release`.

**Comment by tritonas00** [comment]
i tried `cmake -DCMAKE_BUILD_TYPE=Release .` also but it insists on RelWithDebInfo thing though. Anyway, this is very early stage, i'm sure you will fix things in the future. Great work again :+1:  ogre-next looks awesome. Love the atmosphere component, the lighting the shadows. Check out this HLMS water also https://github.com/yoyTeam/OgreOcean

https://www.youtube.com/watch?v=4pxiAFJZhhQ

**Comment by cryham** [comment]
Yeah I agree.
I did, and I want to someday include this Ocean here too :smiley:
